version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tiktok-backend
    volumes:
      - ./videos:/videos
    ports:
      - "8000:8000"
    environment:
      - HOST_IP=0.0.0.0  # FastAPI host
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_SERVER_HOST: http://192.168.0.194:8000
    container_name: tiktok-frontend
    ports:
      - "3015:80"
    depends_on:
      - backend
    restart: unless-stopped
